<?php 
  $config = Mage::helper('ditotracking/config'); 
  $dataHelper = Mage::helper('ditotracking/data');
?>

<script>
  (function(d,e,id){
    window.dito={};window._ditoTemp=[];
    dito.generateID=function(str){return'_dito_sha1_'+str;}
    var m=['init','identify','alias','unalias','track'],s=d.createElement('script'),
    x=d.getElementsByTagName(e)[0];s.type='text/javascript';s.async=true;s.id=id;
    s.src='//storage.googleapis.com/dito/sdk.js';x.parentNode.insertBefore(s,x);
    for(var i=0;i<m.length;i++){dito[m[i]]=function(i){
    return function(){_ditoTemp.push({methodName:m[i],params:arguments});}}(i)}
  })(document,'script','dito-jssdk');
</script>

<?php if($config->isDitoEnabled()): ?>
  <input type="hidden" id="_dito-root-path" value="<?php echo Mage::getUrl(); ?>">

  <script type="text/javascript">
    dito.init({
      apiKey: '<?php echo $config->getApiKey(); ?>',
      session: true
    });
    
    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
      <?php if($config->getCacheStrategy()): ?>
        jQuery.get(jQuery('#_dito-root-path').val() + 'ditotracking/index/identify', function(response){
          try {
            eval(response);
          }
          catch(e) {}
        });
      <?php else: ?>
        <?php $customer = $dataHelper->getUserIdentifyObject(); ?>

        <?php if(!empty($customer)): ?>
          dito.identify(<?php echo json_encode($customer) ?>);
        <?php endif; ?>
      <?php endif; ?>
    <?php endif; ?>
  </script>
<?php endif; ?>
