<?php 
  $config = Mage::helper('ditotracking/config');
  $dataHelper = Mage::helper('ditotracking/data');
?>

<?php if($config->getTrackStatus('catalog_product_view')): ?>
  <?php
    $product = Mage::registry('current_product');
    $data = $dataHelper->getProductTrackingObject($product);
  ?>

  <script type="text/javascript">
    dito.track({
      action: 'acessou-produto',
      data: <?php echo json_encode($data); ?>
    });
  </script>
<?php endif; ?>